### ISSUE TITLE
ESM imports to CommonJS

### ISSUE THREAD

**Issue by zardoy** [cmstead/js-codeformer#21]
For example [putout has these transfromers](https://github.com/coderaiser/putout#:~:text=convert%20commonjs%20to%20esm). I believe it's possible to support/reuse them. 

VSCode (actually TS) has builtin refactoring `Convert require to import` when file extension is `.ts` but not vice-versa.

Also, for now I can see here only builtin refactorings. I can use them all without installing this extension (except refactorings that work with frameworks).

**Comment by cmstead** [comment]
I'll have a look through their list and see what makes sense. Some of the actions I see aren't safe without sufficient test support for your code. I'm less interested in a one-to-one feature comparison and more interested in improving day-to-day work.

**Are there specific items on the putout list you'd like to see incorporated that you use frequently?**

Regarding refactorings: yes, the mirrored built-in refactorings are there intentionally to provide a uniform working experience beyond the VS Code supported file types.

Meanwhile, there's a list of other actions available in the plugin which people call "refactorings" and don't fit the definition simply because they aren't guaranteed to change code without changing behavior:

Conversions

Change Variable Type
Convert Expression to Template Literal
Convert Function to Arrow Function
Convert Function to Function Expression
Convert Function Property to Method
Convert Function Variable to Function Declaration
Convert Ternary to If/Else [See known issues]

Actions

Surround with (Contains non-core options)
Introduce variable
Introduce function
Lift and name function expression
Toggle Async Function Property
Toggle Arrow Function Braces
Toggle Function Call Arguments Between Positional and Object Style
Toggle Function Parameters between Positional and Object Destructuring Style
Toggle Property Declaration Between Standard and Shorthand

**Comment by cmstead** [comment]
I did some investigation regarding the actual, stated request: convert esm import to common js (require).

Though there is a straightforward path to convert from common js to esm, there are a couple of cases regarding esm imports that have no common js analog. I am going to figure out which cases I will/won't be able to support smoothly, and error on the ones which cannot be converted.

**Comment by cmstead** [comment]
This is available in the latest release:

https://github.com/cmstead/js-codeformer/releases/tag/v1.29.1

**Comment by zardoy** [comment]
As I understand it can convert only one line of expression, I would really appreciate if I could change 20 lines with onecommand.

**Comment by cmstead** [comment]
I can convert this to a multi-select pretty easily. Select any imports you want to convert (alt+click, alt+cmd/ctl+down-arrow), I'll find the imports, convert them, and ignore anything that doesn't fit.  I already have all the infrastructure for it.

**Comment by cmstead** [comment]
This is all set in the latest release. Multi-select is supported. If you select anything that is not an import, it will be ignored. If you select an unconvertable import, you'll get a message when all convertable imports have been converted.

Cheers!

https://github.com/cmstead/js-codeformer/releases/tag/v1.30.0
